"""added memory and time for problems

Revision ID: 4b687cdfbf6e
Revises: bdd5a481b8b7
Create Date: 2023-10-07 16:59:02.660358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b687cdfbf6e'
down_revision = 'bdd5a481b8b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('max_memory_limit', sa.Float(), nullable=False))
    op.add_column('problems', sa.Column('max_execution_time', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'max_execution_time')
    op.drop_column('problems', 'max_memory_limit')
    # ### end Alembic commands ###
