"""Difficulty changle

Revision ID: 6eaab36ba68f
Revises: c05b4d77948c
Create Date: 2023-10-05 13:42:45.042682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaab36ba68f'
down_revision = 'c05b4d77948c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
