"""changle is_public

Revision ID: a7bfbcaaf61e
Revises: aab3a10fed3e
Create Date: 2023-11-02 01:57:23.596482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bfbcaaf61e'
down_revision = 'aab3a10fed3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_column('assignments', 'isPublic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('isPublic', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('assignments', 'is_public')
    # ### end Alembic commands ###
