"""add dependencies

Revision ID: b1c5c5829493
Revises: e3c518059808
Create Date: 2023-09-26 12:34:09.705256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c5c5829493'
down_revision = 'e3c518059808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
