"""primary_key test changle

Revision ID: bdd5a481b8b7
Revises: 169c47479e93
Create Date: 2023-10-05 15:24:31.009698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd5a481b8b7'
down_revision = '169c47479e93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
