"""add user_id

Revision ID: e3c518059808
Revises: 17852d986c5f
Create Date: 2023-09-26 00:28:35.742052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c518059808'
down_revision = '17852d986c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('submission', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'submission', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'user_id')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
