"""add description problem

Revision ID: fab04303b422
Revises: 4b687cdfbf6e
Create Date: 2023-10-19 22:06:29.376304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab04303b422'
down_revision = '4b687cdfbf6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'description')
    # ### end Alembic commands ###
